// <auto-generated />
using System;
using EllosPratas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EllosPratas.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20250922025910_CriacaoTabelaClientes")]
    partial class CriacaoTabelaClientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EllosPratas.Models.CaixaModel", b =>
                {
                    b.Property<int>("id_caixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_caixa"));

                    b.Property<DateTime>("data_abertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_fechamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_funcionario")
                        .HasColumnType("int");

                    b.Property<int>("id_loja")
                        .HasColumnType("int");

                    b.Property<string>("observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_caixa");

                    b.ToTable("Caixa");
                });

            modelBuilder.Entity("EllosPratas.Models.CategoriaModel", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_categoria"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("nome_categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("EllosPratas.Models.ClienteModel", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cliente"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_cadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EllosPratas.Models.EnderecoModel", b =>
                {
                    b.Property<int>("id_endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_endereco"));

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_endereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("EllosPratas.Models.EstoqueModel", b =>
                {
                    b.Property<int>("id_estoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_estoque"));

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.HasKey("id_estoque");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("EllosPratas.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("id_funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_funcionario"));

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_loja")
                        .HasColumnType("int");

                    b.Property<int>("id_nivel_acesso")
                        .HasColumnType("int");

                    b.Property<string>("nome_funcionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_funcionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("EllosPratas.Models.ItensVendaModel", b =>
                {
                    b.Property<int>("id_item_venda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_item_venda"));

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<int>("id_venda")
                        .HasColumnType("int");

                    b.Property<decimal>("preco_venda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_item_venda");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("EllosPratas.Models.LojaModel", b =>
                {
                    b.Property<int>("id_loja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_loja"));

                    b.Property<string>("id_endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_loja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_loja");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("EllosPratas.Models.PagamentoModel", b =>
                {
                    b.Property<int>("id_pagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pagamento"));

                    b.Property<DateTime>("data_pagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("forma_pagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("parcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("valor_pago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_pagamento");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("EllosPratas.Models.ProdutosModel", b =>
                {
                    b.Property<int>("id_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_produto"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("codigo_barras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("imagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("nome_categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_produto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("preco_venda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.HasKey("id_produto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EllosPratas.Models.VendaModel", b =>
                {
                    b.Property<int>("id_venda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_venda"));

                    b.Property<DateTime>("data_venda")
                        .HasColumnType("datetime2");

                    b.Property<string>("forma_pagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_cliente")
                        .HasColumnType("int");

                    b.Property<int>("id_funcionario")
                        .HasColumnType("int");

                    b.Property<int>("id_loja")
                        .HasColumnType("int");

                    b.Property<decimal>("valor_desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valor_final")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valor_total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_venda");

                    b.ToTable("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
